on:
  push:
    branches:
      - main
jobs:
  build: 
     runs-on: ubuntu-latest
     steps:
        - name: Checkout
          uses: actions/checkout@v3.3.0
        - run: docker build -t shaastra .
          
